### ISSUE TITLE
关于CIoU loss的 alpha 系数

### ISSUE THREAD

**Issue by lucienne999** [Zzh-tju/DIoU-pytorch-detectron#15]
请问一下, 论文里的alpha是一个根据iou的分段函数, 但是代码里是直接计算的. 是因为在计算之前已经过滤掉IoU小于0.5 的 pred bboxes吗?

https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/utils/net.py#L122

**Comment by Zzh-tju** [comment]
下面还会乘iou_weights

**Comment by lucienne999** [comment]
> 下面还会乘iou_weights
好的, 谢谢你的答复~

有看到weight的生成在这个文件下 https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/master/lib/roi_data/rpn.py, 
生成的过程中还是用阈值卡掉了IoU 不符合要求的bbox. 但是如果我在sample proposal的时候这个阈值设置的小于0.5, 那么我是不是应该加上这个条件?

**Comment by Zzh-tju** [comment]
请随意尝试
