### ISSUE TITLE
bbox transform 的问题

### ISSUE THREAD

**Issue by lucienne999** [Zzh-tju/DIoU-pytorch-detectron#16]
您好, 关于仓库中的bbox transform:  https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/utils/net.py#L16

是如何只通过bbox delta 以及trans weight 就得到pred bbox ? 不需要给proposal吗? 
我看到这一行直接赋值 了 pred_ctr_x = dx , 有一点困惑. 
https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/utils/net.py#L26
 谢谢~

**Comment by Zzh-tju** [comment]
这也是我一开始困惑的地方，GIoU作者似乎在这个地方使用delta进行IoU loss的计算，而且似乎一切正常

**Comment by lucienne999** [comment]
> 这也是我一开始困惑的地方，GIoU作者似乎在这个地方使用delta进行IoU loss的计算，而且似乎一切正常

有 link 吗, 我去看一下为什么他这样写. 这样的话等价于回归的输出不再是(dx,dy,dw,dh) 而是 (x,y,w,h), 这样的话应该会增加回归的难度.... 
https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/modeling/fast_rcnn_heads.py#L50
需要注意的是, loss的计算代码中 smooth L1 loss 回归的仍是(dx, dy, dw, dh). 
那么, 名为 bbox_delta 的变量 在不同的loss中扮演了不同的回归目标. 建议区分一下, 不然容易混淆.

**Comment by Zzh-tju** [comment]
https://github.com/generalized-iou/Detectron.pytorch
我们的模型除了新增D/CIoU loss的函数，其他一模一样

**Comment by Hexuanfang** [comment]
> 您好, 关于仓库中的bbox transform:
> 
> https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/utils/net.py#L16
> 
> 是如何只通过bbox delta 以及trans weight 就得到pred bbox ? 不需要给proposal吗?
> 我看到这一行直接赋值 了 pred_ctr_x = dx , 有一点困惑.
> https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/utils/net.py#L26
> 
> 
> 谢谢~

您好，遇到同样的困惑，希望解答，先谢为敬

**Comment by lucienne999** [comment]
> > 您好, 关于仓库中的bbox transform:
> > https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/utils/net.py#L16
> > 
> > 是如何只通过bbox delta 以及trans weight 就得到pred bbox ? 不需要给proposal吗?
> > 我看到这一行直接赋值 了 pred_ctr_x = dx , 有一点困惑.
> > https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/utils/net.py#L26
> > 
> > 谢谢~
> 
> 您好，遇到同样的困惑，希望解答，先谢为敬

他是直接用dxdydwdh 来计算iou的. 和真实的bbox(x1,y1,x2,y2)会有一些差距, 这个差距并不是很大. 举个例子, 
`target = [100.2, 56.7, 120.3, 77.9];
pred = [10.2, 44.7, 110.3, 97.9];
propoals = [99, 54, 126, 80];` 
iou的计算结果是0.0387, 使用delta值来计算是0.0432.  如果完全重叠, 两个值都是1, 完全不重叠, 两个值都是0. 如果更换成真实的bbox也是可以的. 只不过两种loss关注的点不太一样而已, 整体的思想都是一样的, 加强小物体的关注, 在smooth-L1里所有的delta都是等价的, 但是在Iou-based的方法中, 大物体的并集(∪)会更大, 一定程度会削弱大物体在loss中的权重吧, 个人理解.

**Comment by Hexuanfang** [comment]
> > > 您好, 关于仓库中的bbox transform:
> > > https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/utils/net.py#L16
> > > 
> > > 是如何只通过bbox delta 以及trans weight 就得到pred bbox ? 不需要给proposal吗?
> > > 我看到这一行直接赋值 了 pred_ctr_x = dx , 有一点困惑.
> > > https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/6e18f2c9f80c995e8730605de5aaabfa346e88d0/lib/utils/net.py#L26
> > > 
> > > 谢谢~
> > 
> > 
> > 您好，遇到同样的困惑，希望解答，先谢为敬
> 
> 他是直接用dxdydwdh 来计算iou的. 和真实的bbox(x1,y1,x2,y2)会有一些差距, 这个差距并不是很大. 举个例子,
> `target = [100.2, 56.7, 120.3, 77.9]; pred = [10.2, 44.7, 110.3, 97.9]; propoals = [99, 54, 126, 80];`
> iou的计算结果是0.0387, 使用delta值来计算是0.0432. 如果完全重叠, 两个值都是1, 完全不重叠, 两个值都是0. 如果更换成真实的bbox也是可以的. 只不过两种loss关注的点不太一样而已, 整体的思想都是一样的, 加强小物体的关注, 在smooth-L1里所有的delta都是等价的, 但是在Iou-based的方法中, 大物体的并集(∪)会更大, 一定程度会削弱大物体在loss中的权重吧, 个人理解.

感谢解答！
