### ISSUE TITLE
What dose the tourch.max mean in the compute_iou function?

### ISSUE THREAD

**Issue by ustcjerry** [Zzh-tju/DIoU-pytorch-detectron#2]
https://github.com/Zzh-tju/DIoU-pytorch-detectron/blob/88ab044b0f5483ac68c14e8e9f53f1f03669d60b/lib/utils/net.py#L45

It looks like it's not necessary to calculate the max values. Could you please explain this in detail?

**Comment by Zzh-tju** [comment]
we just keep the code as the same to GIoU code

**Comment by ustcjerry** [comment]
Ok.. thanks
