### ISSUE TITLE
ciou

### ISSUE THREAD

**Issue by henbucuoshanghai** [Zzh-tju/DIoU-pytorch-detectron#8]
ciou的系数为何是4除以pi的平方？
ciou为何是如此的公式？原理是什么？
求角度能看懂，别的不懂

**Comment by Zzh-tju** [comment]
压缩长宽比损失从(0,∞)至(0,1)

**Comment by henbucuoshanghai** [comment]
不是很懂ciou 数学原理 有链接吗？多谢多谢

**Comment by Zzh-tju** [comment]
https://arxiv.org/abs/2005.03572
